{{/*
The PodDisruptionBudget object to be created.
*/}}
{{- define "common.pdb" }}
  {{- $fullName := include "common.names.fullname" . -}}
  {{- $pdbName := $fullName -}}
  {{- $values := .Values.podDisruptionBudget -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $pdbName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with $values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $values.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with $values.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
    matchExpressions:
      - key: objectKind
        operator: NotIn
        values:
          - job
          - cronjob
{{- end }}
