# overrides for default chart values, used for CI testing by "ct" tool, see https://github.com/helm/chart-testing/blob/main/doc/ct_install.md
image:
  repository: ealen/echo-server
  tag: latest
env:
  - name: PORT
    value: 8080
  - name: APP_Version
    value: "{{ .Chart.Version }}"
  - name: Dependency_Version
    value: "
{{- range .Chart.Dependencies -}}
{{- with fromJson (toJson .) -}}
{{ .name }}:{{ .version }}
{{- end }}
{{- end }}"
serviceAccount:
  create: true
  name: '{{ .Chart.Name }}-sa'
  annotations:
    iam.gke.io/gcp-service-account: '{{ .Chart.Name }}-sa@local'
podDisruptionBudget:
  minAvailable: 50%
cronjobs:
  job2:
    schedule: 0 */2 * * *
    backoffLimit: 0
    image:
      repository: ealen/echo-server
      tag: latest
