
name: Jira_Issue_Creator

on:
  pull_request:
    types:
      - opened
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot PRs
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
          project: KTL
          issuetype: Task
          summary: ${{ github.event.pull_request.title }}
          description: GitHub PR URL ${{github.event.pull_request.html_url}}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"