name: Lint and Test Charts

on:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Detect changed charts (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Prepare test application chart
        run: |
          export LIB_CHART_VERSION=$(helm show chart ./charts/common/ | grep version | awk '{print $2}')
          echo "This library version: [$LIB_CHART_VERSION]"
          echo "Pack library $LIB_CHART_VERSION locally..."
          mkdir -p ./test-app/charts
          helm package ./charts/common/ --destination ./test-app/charts
          ls -alF ./test-app/charts
          echo "====="
          cat ./test-app/Chart.yaml
          echo "===== Modify test-app chart to use library-chart $LIB_CHART_VERSION ====="
          sed -i "s/\$LIB_CHART_VERSION/$LIB_CHART_VERSION/g" ./test-app/Chart.yaml
          cat ./test-app/Chart.yaml
          echo "====="
          helm dependency list ./test-app/

      - name: Run chart-testing (lint)
        run: ct lint --all --helm-dependency-extra-args ["--skip-refresh"] --config .github/ct-lint.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0
#        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: |
          helm dependency list ./test-app/
          echo "===== helm template ====="
          helm template ./test-app/ --values ./test-app/ci/test-app-values.yaml
          echo "===== installing application to the cluster ====="
          ct install --config .github/ct-install.yaml
