name: Lint and Test Charts

on:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Detect changed charts (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "Changes were detected!"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Prepare test application chart
        run: |
          export LIB_CHART_VERSION=$(helm show chart ./charts/common/ | grep version | awk '{print $2}')
          echo "This library version: [$LIB_CHART_VERSION]"
          echo "====="
          cat ./test-app/Chart.yaml
          echo "===== Modify test-app chart to use library-chart $LIB_CHART_VERSION ====="
          sed -i "s/\$LIB_CHART_VERSION/$LIB_CHART_VERSION/g" ./test-app/Chart.yaml
          cat ./test-app/Chart.yaml
          echo "====="

      - name: Run chart-testing -> lint library
        run: ct lint --validate-maintainers=false --target-branch main

      - name: Run chart-testing -> lint test-app
        # NB: This step creates library package for install step below
        run: ct lint --all --check-version-increment=false --config .github/ct-lint.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
#        if: steps.list-changed.outputs.changed == 'true'

      - name: Verify kind cluster
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -n kube-system

      - name: Run chart-testing -> install test-app
        run: |
          ls -l ./test-app/charts
          echo "===== helm dependency list ====="
          helm dependency list ./test-app/
          echo "===== helm template ====="
          helm template ./test-app/ --values ./test-app/ci/test-app-values.yaml
          echo "===== installing application to the cluster ====="
          ct install --config .github/ct-install.yaml
